### PR TITLE
add Debian12-rpi4 for testing

### PR DESCRIPTION
**Pull request by osnabrugge**
I have ported https://raspi.debian.net/tested/20230612_raspi_4_bookworm.img.xz into PINNs compatible and tested myself on a few devices.  Would like to open this up to the broader community within the os_testing.json file.

Hope this PR is ok?  Let me know if any changes are required.

### CODE REVIEW

**Comment by osnabrugge** [comment]
This pull request updates the `os/os_testing.json` file to add a new operating system entry for Debian Bookworm on Raspberry Pi 4B.

### New OS Entry Added:

* `os/os_testing.json`: Added a new entry for Debian Bookworm for Raspberry Pi 4B, including:
  * Release date
  * Supported models
  * Download size
  * URLs for OS information, partitions, icons, marketing, partition setup, and tarballs

### Relevancy / Next Steps:

@procount 
Given the releases since this PR opened, do you already have a Debian 12 (Bookworm) image that is non-Raspbian and more lightweight (about 75% fewer packages)?

* If **yes**, we can close this PR.
* If **no**:
  * Is a code review and merge quicker than me rebuilding the image?
  * Should I update the image first on the latest PINN release and update the repos, GPG keys, and apps? (It's a minimal headless install, so it shouldn't take much work, although I haven't done any PINN work since this PR was opened.)
* I believe this is a no, but would there be a reason to rebuild as I own other models like Pi2B, CM4, and Pi5? As I recall, those require separate images unless you've found a way to build a cross-platform image for PINN. If separate images are needed, I would have to create separate PRs.

### Please see suggested updates that should help with the PR process
[Previous comment has suggested templates for CODEOWNERS and an Update to README.md](https://github.com/procount/pinn-os/pull/18/commits/083426b3bc652fdab83771ba25e2f5da1412871c), they are more of a template as you would need to decide on the workflow, but I do hope you will allow the PR author to be able to assign you (or others) as a code reviewer which will give you more confidence and change management documentation to ease the approval and merge process.

**Comment by procount** [comment]
Thanks for doing this conversion and updating the necessary meta files.
I'm sorry I've not had much time to do anything on PINN recently and I'm getting a little behind.
I shall try to look at this and merge it.
Regarding the review process, there is really only me, although Lurch is a great help at times. You've taught me something new about CODEOWNERS too, I didn't know that was a thing.

**Comment by osnabrugge** [comment]
# Status Update on PR #18

## Summary of PR (TLDR)

This PR is not urgent and it's your call @procount whether we finish the work to merge (at a slow pace as I am also quite busy) or close this. Its origins are from a personal use case within a HomeLab community project that is continually enhancing an automated template for deploying a flux/gitops k3s cluster. When I opened the PR Debian was supported and highly recommended to be used as the base OS for k3s using a minimal install.  I do not recall if anyone else asked you for this feature too?

 Currently, there's no demand from this community and furthermore, they have adopted Talos and phased out Debian: [Cluster Template](https://github.com/onedr0p/cluster-template).

## Background / Context

SBCs are still supported, and I contributed quite a bit of feedback for the template/community during my experience. Similar to how close the PI5 is to replace your desktop, it's just not quite there yet. I would not recommend any heavy workloads in a K3s cluster made up of PIs. Those who run them, generally don't care about HA or remote access as they're typically just starting out / lack resources.

**Word of caution: Don't mix SBCs with x86_64 in the same cluster.**

Hopefully someone reads this and saves themselves a big headache!  My whole journey started as I urgently needed to reduce power, heat, HVAC demand, etc. Why not dedicate the control plane on Pi4b devices displacing heavier servers? In theory, it should work based on [k3s requirements](https://docs.k3s.io/installation/requirements?os=debian) and performance would be even better today with native PCIe Gen3 NVME speeds. However, while k3s on its own will be perfect, you will run into CNIs and other add-ons that need to run some containers on the control plane that lack arm64 support.  
  
I still leverage SBCs and PINNs, but more for the intended purposes of IoT, edge, etc. and would certainly appreciate the ability to at least have a pre-boot environment like PINNs, but it's not the end of the world if I'm the only person asking for this 😊

## Current Status

Unless there were/are others who have been requesting a minimal footprint of Debian bookworm, the status can still remain low priority. Perhaps demand will increase once it becomes available? I personally like to be as efficient as possible, and I'm sure there are many more.

## Regarding CODEOWNERS

Even if this PR never ends up in the main branch, I'm glad that I was able to provide some value by introducing you to the CODEOWNERS feature. I'm grateful for the opportunity to contribute as I'm still learning every day. Credit must go to [@onedr0p](https://github.com/onedr0p). Either receiving help directly, reverse engineering his repos, or interacting with the community taught me most of what I know in terms of GitOps, Templating, GitHub features, etc.

**Comment by procount** [comment]
I've merged this, but on testing it won't install the boot files. There seems to be some problem installing symlinks

**Pull request merged**
